### ISSUE TITLE
Update version in plugin.yaml for tag 0.10.2

### ISSUE THREAD

**Issue by dani-CO-CN** [chartmuseum/helm-push#134]
It seems that in the last (0.10.2) release the version in plugin.yaml was not increased and is still on version v0.10.1

https://github.com/chartmuseum/helm-push/blob/v0.10.2/plugin.yaml#L2
```yaml
name: "cm-push"
version: "0.10.1"
usage: "Please see https://github.com/chartmuseum/helm-push for usage"
description: "Push chart package to ChartMuseum"
....
```
