### ISSUE TITLE
Helm push lose requirments.yaml file

### ISSUE THREAD

**Issue by yangzb09** [chartmuseum/helm-push#52]
HELM version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
HELM push version: 0.8.0
After upgrade to helm push 0.8.0, The Charts pushed to chartmuseum, lose requirments.yaml. 
```
dependencies:
- name: kube-state-metrics
  version: 2.2.1
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: kube-state-metrics.enabled
- name: A
  version: 1.0.1 
  repository: "file://../A"
  condition: A.enabled
```
Steps to push
```
helm repo add chartmuseum https://charts.software.io
helm dep up software
helm dep build software
helm push software chartmuseum -v ">0.0.0-0" -f 
```
Steps to download
```
wget https://charts.software.io/charts/software-\>0.0.0-0.tgz 
tar zxvf software-\>0.0.0-0.tgz  -C ./dir
s dir
Chart.yaml  charts      templates   values.yaml
```
requirments.yaml and lock are lose.

Anyway, downgrade to 0.7.1 can workaround.
