### ISSUE TITLE
values.yaml comment can not push

### ISSUE THREAD

**Issue by jdolitsky** [chartmuseum/helm-push#97]
I  pushed a chart to repo, but the comment of values.yaml can not be pushed, when the apiVersion in charts.yaml is `v2`, not `v1`

values.yaml conent:
```
## nginx configuration
## Ref: https://github.com/kubernetes/ingress/blob/master/controllers/nginx/configuration.md
##
controller:
  image:
    repository: us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller
    tag: "v0.34.1"
    digest: sha256:0e072dddd1f7f8fc8909a2ca6f65e76c5f0d2fcfb8be47935ae3457e8bbceb20
    pullPolicy: IfNotPresent
    # www-data -> uid 101
    runAsUser: 101
    allowPrivilegeEscalation: true

  # Configures the ports the nginx-controller listens on
  containerPort:
    http: 80
    https: 443

  # Will add custom configuration options to Nginx https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
  config: {}

  ## Annotations to be added to the controller config configuration configmap
  ##
  configAnnotations: {}

```

the content after push to repo:
```
controller:
  image:
    repository: us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller
    tag: "v0.34.1"
    digest: sha256:0e072dddd1f7f8fc8909a2ca6f65e76c5f0d2fcfb8be47935ae3457e8bbceb20
    pullPolicy: IfNotPresent
    runAsUser: 101
    allowPrivilegeEscalation: true
  containerPort:
    http: 80
    https: 443
  config: {}
  configAnnotations: {}
```

Output of `helm version`:

version.BuildInfo{Version:"v3.3.3", GitCommit:"55e3ca022e40fe200fbc855938995f40b2a68ce0", GitTreeState:"clean", GoVersion:"go1.14.9"}

Output of `kubectl version`:

version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T16:54:35Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

cc @dellkeji

**Comment by dellkeji** [comment]
test for push chart by api or helm push plugin：

## by api
```
curl -F "chart=@chart-0.1.38.tgz" http://test.com/api/test/charts
```

the comments in values.yaml are exist


```
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
  - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
```

## by helm push plugin
```
helm push chart-0.1.38.tgz test
```
the comments in values.yaml are deleted
